= TAOドライブ業務委託規約

== 共通条項
.【用語の定義】
第１条 TAOドライブ業務委託規約（以下、本規約といいます。）において使用する以下の用語は、各々以下に定める意味を有するものとします。

1. 甲とはTAOドライブ株式会社を意味します。
2. 乙とは、甲が委託する業務を受託する者を意味します。  
3. 請負契約とは、乙が甲に対して、業務の完成を約する契約を意味します。
4. 準委任契約とは、乙が甲に対して、甲が委託する業務を遂行することを約する契約を意味します。

.【適用範囲】
第２条　本規約は、甲から乙に委託される請負および準委任の業務（以下、本件業務といいます。）に適用されます。 +
２　請負契約には、本規約の共通条項および請負条項が適用されます。 +
３　準委任契約には、本規約の共通条項および準委任条項が適用されます。 

.【個別契約】
第３条　甲と乙は、本規約に基づき甲が乙に委託する本件業務に応じ、請負もしくは準委任を選択して、甲が乙に委託する業務の内容（以下、個別業務といいます。）、委託料、納期もしくは作業期間等を具体的に定めた個別契約を締結するものとします。

.【個別契約の成立および変更】
第４条　個別契約は、甲が乙に発注書を提出し、乙から甲が注文請書を受領した時点もしくは甲の発注後７日以内に乙が文書をもって拒否の申出をしなかったときの何れか早いときに成立します。 +
２ 個別業務の過程において、甲による仕様変更に基づき、作業期間もしくは納期あるいは委託料に変更が及ぶと乙が判断したときは、乙はすみやかに甲に通知し、期間の延長等、個別契約の変更について協議します。 +
３　本規約で定める条項と個別契約の内容に相違がある場合は、個別契約の内容が優先するものとします。

.【権利義務等の譲渡禁止】
第５条　乙は、本規約および個別契約により生じる権利又は義務を第三者に譲渡し、承継させ、または担保の用に供してはなりません。 

.【委託料および支払方法】
第６条　甲は乙に対し、個別業務の対価として、個別契約で定めた委託料を当該契約で定めた方法で支払います。

.【作業期間または納期】
第７条　個別業務の作業期間または納期は、個別業務に係る当該個別契約で定めます。

.【再委任】
第８条　乙は、個別契約の業務の全部または一部を第三者に行わせてはなりません。ただし、甲へ書面による事前の申請を行い、甲の承諾を得た場合は、この限りではありません。

.【担当員】
第９条　乙は、甲のために適正と思われる個別業務担当員を任意に選任できるものとします。 +
２　甲および乙は、個別契約締結後すみやかに、個別業務を円滑に遂行するため、それぞれ個別業務の主任担当者を１名および必要な作業推進体制を定め、互いに書面をもって相手方に通知します。この変更を行った場合も同様とします。 +
３　甲および乙は、個別契約に定めた事項のほか、個別業務遂行に関する相手方からの要請、指示等の受理及び相手方への依頼、その他相手方との連絡、確認等は原則として主任担当者を通じて行うものとします。 +
４　乙の選任した担当員が、疾病、退職その他乙の支配することのできない事由により、個別契約に基づき予定された個別業務処理の履行ができない場合には、乙は適切な期間内に他の担当員と交替させるものとします。

.【権利の帰属】
第１０条　個別業務遂行の過程で生じた、または個別業務の提出物および納品物についての所有権や知的財産権は、甲が保持するものとします。

.【責任】
第１１条　本規約および個別契約における、乙の責めに帰すべき事由による、乙の甲に対する損害賠償責任は、通常想定される因果関係の範囲の損害について負うものとします。

.【秘密情報の取扱】
第１２条　個別契約に関する秘密情報の取扱は、別途、機密保持契約書を締結するものとします。

.【不可抗力免責】
第１３条　甲または乙は、天変地異、戦争、内乱、暴動、法令の改廃、制定、ストライキ、ロックアウトその他の労働争議、その他自己の責に帰すべからざる事由による本規約および個別契約の履行の遅滞、履行不能若しくは不完全履行については、その責に任じないものとします。

.【解除】
第１４条　甲または乙は、相手方が次の各号の一つにでも該当する場合には、相手方に対し何らの催告をも行わずに本規約および個別契約の全部又は一部を解除することができます。

1. 本規約または個別契約の条項に違反したとき。
2. 正当な理由なく本規約または個別契約上の義務を履行しないか、又は履行の見込みがないと認められるとき。
3. 本規約または個別契約の履行に関し、不正又は不当な行為があったとき。
4. 監督官庁より営業停止、営業免許若しくは営業登録の取消処分を受けたとき。
5. 差押、仮差押、仮処分、競売、強制執行又は公租公課、社会保険料等の滞納処分を受けたとき。
6. 破産、民事再生手続開始、又は会社更生手続開始、会社整理開始又は特別清算開始の申し立てをされたとき、若しくは自ら申し立てたとき。
7. 自ら振出し又は引受けた手形又は小切手につき不渡処分を受けたとき。
8. 財産状態が悪化し、またはその恐れが認められる相当の理由があるとき。
9. 甲または乙が、相手方ののれん又は信用を害する行為を行ったとき。

２　両者は、前項各号の一に記載の事由が生した場合には、ただちにその旨を相手方に通知するものとします。 +
３　第１０条（権利の帰属）、第１２条（秘密情報の取扱）、第１３条（不可抗力免責）、第１４条（解除）、第１６条（合意管轄）の規定は、本規約および個別契約が如何なる理由により終了した場合においても、引き続き有効とします。

.【完全合意】
第１５条　本規約および個別契約は、個別契約の締結日現在における甲、乙双方の完全な合意を構成し、個別契約締結日以前に甲乙間で為された合意内容に取って代わるものです。当該合意内容と個別契約内容に相違がある場合は、本規約および個別契約が優先するものとします。個別契約は、各当事者の署名又は記名捺印する書面による以外は、修正されないものとします。

.【合意管轄】
第１６条　本規約および個別契約の解釈若しくは有効性又は当事者の権利及び責任に関する当事者間の見解の相違又は紛争は、東京地方裁判所を第一審の専属合意管轄裁判所とします。

== 請負条項

.【納入】
第１条　乙は甲に対し、個別契約で定める納期までに、個別契約所定の納品物を納入します。

.【検査と検収】
第２条　甲は、納入があった場合、検査を行い、合否を判定します。 +
２　甲は、納品物が前項の検査に合格しない場合、修正又は追完を求めるものとします。乙は、協議の上定めた期限内に無償で修正して甲に納入し、甲は必要となる範囲で、前項所定の検査を再度行うもとします。 +
３　本条所定の検査合格をもって、納品物の検収完了とします。

.【危険負担】
第３条　納入物の滅失、毀損等の危険負担は、納入前については乙が、納入後については甲が、それぞれこれを負担するものとします。

.【不適合】
第４条 本規約請負条第２条の検収完了後、納品物に不適合が発見された場合、甲および乙は、不適合の原因について協議・調査するものとします。協議・調査の結果、当該不適合が乙の責に帰すものであると認められた場合、甲は乙に対して当該不適合の修補を請求することができ、乙は、当該不適合を修補するものとします。なお、乙が係る修補の責任を負うのは、検収完了後６ヶ月以内に甲から請求がなされた場合に限るものとします。

== 準委任条項

.【業務の遂行】
第１条　乙は、個別業務を発注書、プロジェクト計画書または仕様書、打ち合わせ、甲乙の協議等に従い処理し、定期的に甲に対して業務遂行状況の報告を行い、承認を得ます。

.【業務の確認】
第２条　乙は、個別契約に定める作業期間の満了もしくは個別契約に定める作業時間分の作業実施完了のいずれか早い時点からすみやかに甲に報告します。 +
２　甲は、当該報告の内容に疑義がない場合、報告の完了をもって個別業務の終了を確認するものとします。

附則 +
本規約は平成２８年１０月１日から施行します。

令和３年４月１日改定
